server.port=8083
spring.application.name=cart-service
spring.cloud.compatibility-verifier.enabled=false

spring.data.mongodb.uri=mongodb://localhost:27017/cartdb

jwt.secret=${JWT_SECRET:ecommerce-demo-jwt-secret-key-change-me-min-32-chars}
app.cookie.name=token


springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.persistAuthorization=true

logging.level.com.ecommerce=INFO

feign.circuitbreaker.enabled=true
feign.client.config.default.connectTimeout=3000
feign.client.config.default.readTimeout=5000

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
